### PR TITLE
Bootstrap CloudFormation Enhancements

### PR DESCRIPTION
**Pull request by janeuner**
This PR adds:
- the ability to specify multiple IAM policies
- context-appropriate path for the IAM role
- default changed to ReadOnlyAccess 

Signed-off-by: Jarod Neuner <janeuner@gmail.com>

### CODE REVIEW

**Comment by janeuner** [comment]
Also added logic to suppress AWS credentials calls when secrets are not configured on the repo (ie, for this template).

**Review by kajalnp — COMMENTED** [review]
In .github/workflows/tfmain.yml: Are you testing AWS Cred. just wanted to make sure. Is this needed in the long run, initially it may be a good idea to test, right?

**Comment by janeuner** [comment]
@kajalnp The Test AWS Credentials was originally for debugging, but I left it in because it effectively logs the identity used to execute the workflow.

**Review by kajalnp — APPROVED** [review]
LGTM.

**Pull request merged**
